apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kubnahum-bc44"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kubnahum-bc44"
  template:
    metadata:
      labels:
        app: "kubnahum-bc44"
    spec:
      containers:
        - name: "kubnahum-bc44"
          image: "acrdemo1207.azurecr.io/kubnahum"
          ports:
          - containerPort: 80