apiVersion: v1
kind: Service
metadata:
    name: "kubnahum-bc44"
    labels:
        app: "kubnahum-bc44"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kubnahum-bc44"